### ISSUE TITLE
ballyregan.core.exceptions.NoInternetConnection

### ISSUE THREAD

**Issue by jhautefeuille** [idandaniel/ballyregan#17]
Linux pop7550 6.0.6-76060006-generic #202210290932~1669062050~22.04~d94609a SMP PREEMPT_DYNAMIC Mon N x86_64 x86_64 x86_64 GNU/Linux

Python 3.10.6

julien@pop7550:~$ ballyregan get --all
Traceback (most recent call last):
  File "/home/julien/.local/bin/ballyregan", line 5, in <module>
    from cli.app import run
  File "/home/julien/.local/lib/python3.10/site-packages/cli/app.py", line 14, in <module>
    fetcher = ProxyFetcher()
  File "<string>", line 7, in __init__
  File "/home/julien/.local/lib/python3.10/site-packages/ballyregan/fetcher.py", line 37, in __post_init__
    raise NoInternetConnection
ballyregan.core.exceptions.NoInternetConnection

**Comment by Fiattarone** [comment]
All CLI get commands are resulting in this error

**Comment by perelin** [comment]
seems `sudo` helps. At least on macOS
